### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-rs#109]
- [x] JSON-RPC API protocol (#105)
- [x] JSON-RPC API implementation (#112)
- [x] Hide/unhide accounts (#130)
- [x] Replace `rust-crypto` (#87)
- [x] Initial CLI impl. (#110)
- [x] ~~Publish binary artifacts on bintray (#137)~~
- [x] Bump version to 0.9 (after all else)

**Comment by dulanov** [comment]
@splix @r8d8 @sjmackenzie @sorpaas this task accumulates the set of subtasks for public beta version, then we release first version, ideally before our anniversary - [Jul 20, 2016 3:20 PM](https://gastracker.io/block/0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f).

**Comment by dulanov** [comment]
@sorpaas can you help mainly with JSON RPC endpoint impl.?

**Comment by sorpaas** [comment]
@dulanov So you basically mean this file https://github.com/ethereumproject/emerald-rs/pull/108/files#diff-9d8bb2c91f8003393b2bdcdfbd779989 to be implemented, right?

**Comment by dulanov** [comment]
@sorpaas absolutely, but this is not done yet, just draft version.

**Comment by sorpaas** [comment]
Okay, I can work on that.

**Comment by dulanov** [comment]
This version has a direct relationship to https://github.com/ethereumproject/emerald-wallet/issues/121.

**Comment by dulanov** [comment]
@sorpaas and it's also up to you to change impl., `jsonrpc` works good, but a little bit magic, you can reimpl. directly with Hyper, for example.
