### ISSUE TITLE
CLI release

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-rs#213]
Expecting release by end of the month

## Bugfixes

 - [x] expects password for Ledger sign - #216

## New Features

 - [x] keep private keys in database (discuss) - #169
 - [x] send value transaction from command line - #214 
 - [x] more informative errors when invalid JSON passed - #215 
 - [x] if chain passed in both request and cli, make sure it's same (discuss)

## Improvements

- [x] Delete accounts - #218

## Other

 - [x] binary builds to builds.etcdevteam.com
